name: spec2uml
description: "AI-powered UML generator app for students and system designers."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Core
  get: ^4.7.2
  http: ^1.4.0

  # UI & Media
  flutter_svg: ^2.2.0
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.1

  # Input & File Handling
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  speech_to_text: ^7.1.0
  syncfusion_flutter_pdf: ^30.1.38

  # AI Support
  google_ml_kit: ^0.20.0

  # UX
  clipboard: ^0.1.3
  file_saver: ^0.3.0
  get_storage: ^2.1.1
  webview_flutter_android: ^4.7.0
  archive: ^4.0.7
  image_gallery_saver_plus: ^4.0.1
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  flutter_html: ^3.0.0
  markdown: ^7.3.0
  photo_view: ^0.15.0
  google_fonts: ^6.2.1
  flutter_markdown_plus: ^1.0.3
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appLogo.png"
  adaptive_icon_foreground: "assets/appLogo.png"
  adaptive_icon_background: "#FFFFFF"


flutter:
  uses-material-design: true

  assets:
    - assets/appLogo.png
    - assets/splash.png
    - assets/main.png
    - assets/auto.png
    - assets/robot.png
    - assets/splashRobo.png

